### ISSUE TITLE
Canu Triobinning on Cannabis sativa L.

### ISSUE THREAD

**Issue by KevinMcKernan** [skoren/triobinningScripts#4]
We have a trio sequenced on PacBio Sequel II V6 with CLR chemistry. 30-40kb reads and over 100X coverage for each. The independent FALCON-UNZIP assemblies are over 2mb N50. Genome is 876Mb, 10/20 chromosomes (haploid/diploid). XY sex system with Y being the largest chromosome (~118Mb).

F0 generation are siblings. Jamaican Lion Mother X Jamaican Lion Father
F1 generation is JL5
SNP every 94 bases (N=40 WGS on ILMN). ~3X lower in this inbred cross. 
66% AT. Repeat rich (26kb LTR & tandem LTRs).

Summary of the results in the linked ppt.
https://www.dropbox.com/s/pcak1jv89ngid0e/JL5_trio.pptx?dl=0

The higher kmer number in the father is bizarre. We are curious if there are any parameters we should adjust given the FALCON assemblies seems to make good independent assemblies with 93-97% BUSCO completion scores.

Thank you in advance for any assistance.

From: Greg
I used: Canu snapshot v1.8 +261 changes (r9471 093a51f41fcb7029a81dfd7663ee5aa4e44e2110)”
to do the trio binning - here is the exact script I used: 

###Trio Binning Script
#!/bin/bash

source /mnt/software/Modules/current/init/bash

module load jdk/1.8.0_60
module load gcc/6.4.0
CANU_HOME=/home/UNIXHOME/gconcepcion/src/github/canu/Linux-amd64/bin
INPUT=$(readlink -f ${1})
echo ${INPUT}

${CANU_HOME}/canu -p JL5_trio \
    -d JL5_trio \
    -haplotype \
    -useGrid=false \
    genomeSize=1000m \
    -haplotypeFather /pbi/dept/appslab/datasets/medicinalGenomics/Sample_*father.fasta \
    -haplotypeMother /pbi/dept/appslab/datasets/medicinalGenomics/Sample_*mother.fasta \
    -pacbio-raw ${INPUT}

**Comment by skoren** [comment]
Those binned reads sets do not look healthy, I wouldn't have bothered assembling. All the coverage went to the mother and so the father probably didn't have enough coverage to get a good assembly. For trios, we recommended in the paper to select homozygous parents that are unrelated to each other, this example has the opposite, selecting heterozygous parents which are very closely related and likely share large stretches of homology. 

1. Is there equal coverage of the mother and father input for illumina data? This could explain the large difference in k-mers between the parents if it's not equal
2. Count how many k-mers exist in the mother and not in the father and in the offspring (assuming you have illumina data for the offspring) and the same for the father. I want to see if those are close or not. I would guess the offspring has a Y? I think what happened here is the use of siblings made the autosomes close but the Y is quite distinct since only one parent has it which is inflating the paternal k-mer set.
3. Try binning using the python script in this repo but edit it to not scale kmer counts by set size. This is deflating the count of the father markers due to the inflated k-mer set size. To do that, comment out lines 62-64 in classify.py.

**Comment by gconcepcion** [comment]
Hi Sergey,
I agree, the coverage is very lopsided and basically the "opposite" of the recommended dataset - e.g. "inbred siblings" VS "outcrossed strains" - nevertheless we figured we'd give it a try to see what sort of results we got. 

1. Assuming a 1.0Gb genome size - we have roughly 125fold Paternal, and 145 fold Maternal coverage in the illumina short reads. Do you think downsampling the Maternal illumina dataset to roughly 125fold might even out the lopsided binning?

2.  Let me count some kmers and get back to you on this one

**Comment by skoren** [comment]
Idle
